package com.petpacket.final_project.Enum;

import java.time.LocalDateTime;
import java.util.List;

import com.petpacket.final_project.entities.Revenue;
import com.petpacket.final_project.entities.user.User;

public class EmailTemplate {

	public static String emailInvoiceTemplate(String email, User user, List<Revenue> listRevenues, double amount) {
		String bill = "";
		for (Revenue revenue : listRevenues) {
			bill += "<tr>\r\n" + "<td>" + revenue.getBooking().getService().getName() + "</td>\r\n"
					+ "<td class=\"alignright\">" + revenue.getBooking().getTransaction().getAmountPaid()
					+ " VND</td>\r\n" + "</tr>\r\n";
		}
		bill += " <tr class=\"total\">\r\n" + "<td class=\"alignright\" width=\"80%\">Total</td>\r\n"
				+ "<td class=\"alignright\">" + amount + " VND</td>\r\n" + "</tr>";

		String template = "<html><table class=\"body-wrap\">\r\n" + "    <tbody><tr>\r\n" + "        <td></td>\r\n"
				+ "        <td class=\"container\" width=\"600\">\r\n" + "            <div class=\"content\">\r\n"
				+ "                <table class=\"main\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\">\r\n"
				+ "                    <tbody><tr>\r\n"
				+ "                        <td class=\"content-wrap aligncenter\">\r\n"
				+ "                            <table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\">\r\n"
				+ "                                <tbody><tr>\r\n"
				+ "                                    <td class=\"content-block\">\r\n"
				+ "                                        <h2>Thanks for using our app</h2>\r\n"
				+ "                                    </td>\r\n" + "                                </tr>\r\n"
				+ "                                <tr>\r\n"
				+ "                                    <td class=\"content-block\">\r\n"
				+ "                                        <table class=\"invoice\">\r\n"
				+ "                                            <tbody><tr>\r\n"
				+ "                                                <td>" + user.getName() + "<br>Invoice <br>"
				+ LocalDateTime.now() + "</td>\r\n" + "</tr>\r\n"
				+ "                                            <tr>\r\n"
				+ "                                                <td>\r\n"
				+ "                                                    <table class=\"invoice-items\" cellpadding=\"0\" cellspacing=\"0\">\r\n"
				+ "                                                        <tbody>" + bill
				+ "                                                    </tbody></table>\r\n"
				+ "                                                </td>\r\n"
				+ "                                            </tr>\r\n"
				+ "                                        </tbody></table>\r\n"
				+ "                                    </td>\r\n" + "                                </tr>\r\n"
				+ "                                <tr>\r\n"
				+ "                                    <td class=\"content-block\">\r\n"
				+ "                                        <a href=\"#\">View in browser</a>\r\n"
				+ "                                    </td>\r\n" + "                                </tr>\r\n"
				+ "                                <tr>\r\n"
				+ "                                    <td class=\"content-block\">\r\n"
				+ "                                        Pet Service Connect Inc. 193 Nguyen Luong Bang\r\n"
				+ "                                    </td>\r\n" + "                                </tr>\r\n"
				+ "                            </tbody></table>\r\n" + "                        </td>\r\n"
				+ "                    </tr>\r\n" + "                </tbody></table>\r\n"
				+ "                <div class=\"footer\">\r\n" + "                    <table width=\"100%\">\r\n"
				+ "                        <tbody><tr>\r\n"
				+ "                            <td class=\"aligncenter content-block\">Questions? Email <a href=\"mailto:\">petserviceconnect@gmail.com</a></td>\r\n"
				+ "                        </tr>\r\n" + "                    </tbody></table>\r\n"
				+ "                </div></div>\r\n" + "        </td>\r\n" + "        <td></td>\r\n" + "    </tr>\r\n"
				+ "</tbody></table>" + "<style>* {\r\n" + "    margin: 0;\r\n" + "    padding: 0;\r\n"
				+ "    font-family: \"Helvetica Neue\", \"Helvetica\", Helvetica, Arial, sans-serif;\r\n"
				+ "    box-sizing: border-box;\r\n" + "    font-size: 14px;\r\n" + "}\r\n" + "\r\n" + "img {\r\n"
				+ "    max-width: 100%;\r\n" + "}\r\n" + "\r\n" + "body {\r\n"
				+ "    -webkit-font-smoothing: antialiased;\r\n" + "    -webkit-text-size-adjust: none;\r\n"
				+ "    width: 100% !important;\r\n" + "    height: 100%;\r\n" + "    line-height: 1.6;\r\n" + "}\r\n"
				+ "\r\n" + "/* Let's make sure all tables have defaults */\r\n" + "table td {\r\n"
				+ "    vertical-align: top;\r\n" + "}\r\n" + "\r\n" + "/* -------------------------------------\r\n"
				+ "    BODY & CONTAINER\r\n" + "------------------------------------- */\r\n" + "body {\r\n"
				+ "    background-color: #f6f6f6;\r\n" + "}\r\n" + "\r\n" + ".body-wrap {\r\n"
				+ "    background-color: #f6f6f6;\r\n" + "    width: 100%;\r\n" + "}\r\n" + "\r\n" + ".container {\r\n"
				+ "    display: block !important;\r\n" + "    max-width: 600px !important;\r\n"
				+ "    margin: 0 auto !important;\r\n" + "    /* makes it centered */\r\n"
				+ "    clear: both !important;\r\n" + "}\r\n" + "\r\n" + ".content {\r\n" + "    max-width: 600px;\r\n"
				+ "    margin: 0 auto;\r\n" + "    display: block;\r\n" + "    padding: 20px;\r\n" + "}\r\n" + "\r\n"
				+ "/* -------------------------------------\r\n" + "    HEADER, FOOTER, MAIN\r\n"
				+ "------------------------------------- */\r\n" + ".main {\r\n" + "    background: #fff;\r\n"
				+ "    border: 1px solid #e9e9e9;\r\n" + "    border-radius: 3px;\r\n" + "}\r\n" + "\r\n"
				+ ".content-wrap {\r\n" + "    padding: 20px;\r\n" + "}\r\n" + "\r\n" + ".content-block {\r\n"
				+ "    padding: 0 0 20px;\r\n" + "}\r\n" + "\r\n" + ".header {\r\n" + "    width: 100%;\r\n"
				+ "    margin-bottom: 20px;\r\n" + "}\r\n" + "\r\n" + ".footer {\r\n" + "    width: 100%;\r\n"
				+ "    clear: both;\r\n" + "    color: #999;\r\n" + "    padding: 20px;\r\n" + "}\r\n"
				+ ".footer a {\r\n" + "    color: #999;\r\n" + "}\r\n"
				+ ".footer p, .footer a, .footer unsubscribe, .footer td {\r\n" + "    font-size: 12px;\r\n" + "}\r\n"
				+ "\r\n" + "/* -------------------------------------\r\n" + "    TYPOGRAPHY\r\n"
				+ "------------------------------------- */\r\n" + "h1, h2, h3 {\r\n"
				+ "    font-family: \"Helvetica Neue\", Helvetica, Arial, \"Lucida Grande\", sans-serif;\r\n"
				+ "    color: #000;\r\n" + "    margin: 40px 0 0;\r\n" + "    line-height: 1.2;\r\n"
				+ "    font-weight: 400;\r\n" + "}\r\n" + "\r\n" + "h1 {\r\n" + "    font-size: 32px;\r\n"
				+ "    font-weight: 500;\r\n" + "}\r\n" + "\r\n" + "h2 {\r\n" + "    font-size: 24px;\r\n" + "}\r\n"
				+ "\r\n" + "h3 {\r\n" + "    font-size: 18px;\r\n" + "}\r\n" + "\r\n" + "h4 {\r\n"
				+ "    font-size: 14px;\r\n" + "    font-weight: 600;\r\n" + "}\r\n" + "\r\n" + "p, ul, ol {\r\n"
				+ "    margin-bottom: 10px;\r\n" + "    font-weight: normal;\r\n" + "}\r\n" + "p li, ul li, ol li {\r\n"
				+ "    margin-left: 5px;\r\n" + "    list-style-position: inside;\r\n" + "}\r\n" + "\r\n"
				+ "/* -------------------------------------\r\n" + "    LINKS & BUTTONS\r\n"
				+ "------------------------------------- */\r\n" + "a {\r\n" + "    color: #1ab394;\r\n"
				+ "    text-decoration: underline;\r\n" + "}\r\n" + "\r\n" + ".btn-primary {\r\n"
				+ "    text-decoration: none;\r\n" + "    color: #FFF;\r\n" + "    background-color: #1ab394;\r\n"
				+ "    border: solid #1ab394;\r\n" + "    border-width: 5px 10px;\r\n" + "    line-height: 2;\r\n"
				+ "    font-weight: bold;\r\n" + "    text-align: center;\r\n" + "    cursor: pointer;\r\n"
				+ "    display: inline-block;\r\n" + "    border-radius: 5px;\r\n"
				+ "    text-transform: capitalize;\r\n" + "}\r\n" + "\r\n"
				+ "/* -------------------------------------\r\n" + "    OTHER STYLES THAT MIGHT BE USEFUL\r\n"
				+ "------------------------------------- */\r\n" + ".last {\r\n" + "    margin-bottom: 0;\r\n" + "}\r\n"
				+ "\r\n" + ".first {\r\n" + "    margin-top: 0;\r\n" + "}\r\n" + "\r\n" + ".aligncenter {\r\n"
				+ "    text-align: center;\r\n" + "}\r\n" + "\r\n" + ".alignright {\r\n" + "    text-align: right;\r\n"
				+ "}\r\n" + "\r\n" + ".alignleft {\r\n" + "    text-align: left;\r\n" + "}\r\n" + "\r\n"
				+ ".clear {\r\n" + "    clear: both;\r\n" + "}\r\n" + "\r\n"
				+ "/* -------------------------------------\r\n" + "    ALERTS\r\n"
				+ "    Change the class depending on warning email, good email or bad email\r\n"
				+ "------------------------------------- */\r\n" + ".alert {\r\n" + "    font-size: 16px;\r\n"
				+ "    color: #fff;\r\n" + "    font-weight: 500;\r\n" + "    padding: 20px;\r\n"
				+ "    text-align: center;\r\n" + "    border-radius: 3px 3px 0 0;\r\n" + "}\r\n" + ".alert a {\r\n"
				+ "    color: #fff;\r\n" + "    text-decoration: none;\r\n" + "    font-weight: 500;\r\n"
				+ "    font-size: 16px;\r\n" + "}\r\n" + ".alert.alert-warning {\r\n" + "    background: #f8ac59;\r\n"
				+ "}\r\n" + ".alert.alert-bad {\r\n" + "    background: #ed5565;\r\n" + "}\r\n"
				+ ".alert.alert-good {\r\n" + "    background: #1ab394;\r\n" + "}\r\n" + "\r\n"
				+ "/* -------------------------------------\r\n" + "    INVOICE\r\n"
				+ "    Styles for the billing table\r\n" + "------------------------------------- */\r\n"
				+ ".invoice {\r\n" + "    margin: 40px auto;\r\n" + "    text-align: left;\r\n" + "    width: 80%;\r\n"
				+ "}\r\n" + ".invoice td {\r\n" + "    padding: 5px 0;\r\n" + "}\r\n" + ".invoice .invoice-items {\r\n"
				+ "    width: 100%;\r\n" + "}\r\n" + ".invoice .invoice-items td {\r\n"
				+ "    border-top: #eee 1px solid;\r\n" + "}\r\n" + ".invoice .invoice-items .total td {\r\n"
				+ "    border-top: 2px solid #333;\r\n" + "    border-bottom: 2px solid #333;\r\n"
				+ "    font-weight: 700;\r\n" + "}\r\n" + "\r\n" + "/* -------------------------------------\r\n"
				+ "    RESPONSIVE AND MOBILE FRIENDLY STYLES\r\n" + "------------------------------------- */\r\n"
				+ "@media only screen and (max-width: 640px) {\r\n" + "    h1, h2, h3, h4 {\r\n"
				+ "        font-weight: 600 !important;\r\n" + "        margin: 20px 0 5px !important;\r\n"
				+ "    }\r\n" + "\r\n" + "    h1 {\r\n" + "        font-size: 22px !important;\r\n" + "    }\r\n"
				+ "\r\n" + "    h2 {\r\n" + "        font-size: 18px !important;\r\n" + "    }\r\n" + "\r\n"
				+ "    h3 {\r\n" + "        font-size: 16px !important;\r\n" + "    }\r\n" + "\r\n"
				+ "    .container {\r\n" + "        width: 100% !important;\r\n" + "    }\r\n" + "\r\n"
				+ "    .content, .content-wrap {\r\n" + "        padding: 10px !important;\r\n" + "    }\r\n" + "\r\n"
				+ "    .invoice {\r\n" + "        width: 100% !important;\r\n" + "    }\r\n" + "}</style></html>";
		return template;
	}

}
